package model

import (
	"time"

	"github.com/google/uuid"
)

// InvestigationFinding stores the result of a single Investigator search
// dispatched by a side during a trial. Unlike Evidence, a Finding is
// automatically generated by the Investigator (not user-submitted) and is
// always visible to both sides — like a real court transcript recording
// what each lawyer asked the investigator to look up.
//
// Findings do NOT influence belief engines and do NOT show up in the user-
// facing evidence list. The CoT panel and dedicated Investigator panel are
// the only UIs that surface them.
type InvestigationFinding struct {
	ID             uuid.UUID `gorm:"type:uuid;primary_key;default:gen_random_uuid()" json:"id"`
	FindingUUID    string    `gorm:"type:varchar(36);uniqueIndex;not null" json:"finding_uuid"`
	SessionID      uuid.UUID `gorm:"type:uuid;index;not null" json:"session_id"`
	Dispatcher     string    `gorm:"type:varchar(50);not null" json:"dispatcher"`
	Investigator   string    `gorm:"type:varchar(50);not null;default:'investigator'" json:"investigator"`
	Query          string    `gorm:"type:text;not null" json:"query"`
	Summary        string    `gorm:"type:text;not null" json:"summary"`
	ResultCount    int       `gorm:"default:0" json:"result_count"`
	SourceProvider string    `gorm:"type:varchar(30);not null" json:"source_provider"`
	A2AMessageID   *uuid.UUID `gorm:"type:uuid" json:"a2a_message_id,omitempty"`
	CreatedAt      time.Time `json:"created_at"`

	// Optional: store the raw search-result payload (≤ a few KB) so we can
	// re-render the summary without re-running the search. Stored as JSONB
	// so different providers can keep their native shape.
	RawResult StringSlice `gorm:"type:jsonb;default:'[]'" json:"raw_result,omitempty"`
}